### ISSUE TITLE
Adding Swagger to FunctionsAppStartup

### ISSUE THREAD

**Issue by dh-technology-co-uk** [yuka1984/azure-functions-extensions-swashbuckle#19]
Hi,

I'm trying to add swagger to my Azure Functions 2.0 app which is using dependency injection using the FunctionsStartup attribute. Most of the documentation below is suggesting that I need to use a startup class using the WebJobsStartup attribute. 

Could you please let me know if this is possible?

Thanks

**Comment by LockTar** [comment]
Isn't this a duplicate of issue #3?

**Comment by dh-technology-co-uk** [comment]
> Isn't this a duplicate of issue #3?

Thanks @LockTar I didn't see this, will close this and watch the other thread

**Comment by LockTar** [comment]
I tried to investigate last week the difference between `WebJobsStartup` and `FunctionsStartup` because I had the same problem as you when I start using the package but I couldn't get a clear answer. Do you have a page, blogpost or something were the difference is explained?

I changed my code **to** `WebJobsStartup` and everything was still working...
